version: 2.1
jobs:
  build-and-push:
    environment:
      IMAGE_NAME: std4453/jellyfin-vaapi
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Push image to Docker Hub
          command: |
            echo "$DOCKERHUB_ACCESS_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
workflows:
  commit:
    jobs:
      - build-and-push:
          context:
            - docker-hub
          filters:
            branches:
              only: master
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"   # try to rebuild and push every day
          filters:
            branches:
              only:
                - master
    jobs:
      - build-and-push:
          context:
            - docker-hub 
